"""add fields to groups and members tables

Revision ID: 1f8a2562c844
Revises: 80d2da576625
Create Date: 2026-03-03 15:01:36.572578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f8a2562c844'
down_revision: Union[str, Sequence[str], None] = '80d2da576625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('global_prompt', sa.Text(), nullable=True))
    op.add_column('groups', sa.Column('group_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('members', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('members', sa.Column('additional_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'additional_prompt')
    op.drop_column('members', 'is_admin')
    op.drop_column('groups', 'group_settings')
    op.drop_column('groups', 'global_prompt')
    # ### end Alembic commands ###
