"""add telegram_id and admin_id to groups

Revision ID: 2bbd86c3638c
Revises: 7d9197e0d689
Create Date: 2026-03-02 21:36:34.567422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbd86c3638c'
down_revision: Union[str, Sequence[str], None] = '7d9197e0d689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('groups', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'groups', 'userbots', ['admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'admin_id')
    op.drop_column('groups', 'telegram_id')
    # ### end Alembic commands ###
