"""add style settings to userbots

Revision ID: 33edd7811e71
Revises: c414c1e38693
Create Date: 2026-03-03 17:19:08.438070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33edd7811e71'
down_revision: Union[str, Sequence[str], None] = 'c414c1e38693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbots', sa.Column('style_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{"allow_profanity": false, "use_punctuation": true, "use_uppercase": true, "send_photos": false, "gender": "male", "send_stickers": false, "use_ascii_emoticons": false, "message_length": "medium"}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbots', 'style_settings')
    # ### end Alembic commands ###
