"""add trusted_id and message_history table

Revision ID: 4c309da6e392
Revises: 1f8a2562c844
Create Date: 2026-03-03 15:35:34.751677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c309da6e392'
down_revision: Union[str, Sequence[str], None] = '1f8a2562c844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbots', sa.Column('trusted_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbots', 'trusted_id')
    # ### end Alembic commands ###
