"""create contacts table

Revision ID: 80d2da576625
Revises: 2bbd86c3638c
Create Date: 2026-03-03 14:09:41.111690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d2da576625'
down_revision: Union[str, Sequence[str], None] = '2bbd86c3638c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contacts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('userbot_id', sa.UUID(), nullable=False),
        sa.Column('contact_userbot_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['contact_userbot_id'], ['userbots.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['userbot_id'], ['userbots.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('userbot_id', 'contact_userbot_id', name='uq_userbot_contact')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
