"""add conversation settings to groups

Revision ID: c414c1e38693
Revises: 4f8166cde480
Create Date: 2026-03-03 16:52:36.362756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c414c1e38693'
down_revision: Union[str, Sequence[str], None] = '4f8166cde480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('groups', sa.Column('context_messages_count', sa.Integer(), server_default='10', nullable=False))
    op.add_column('groups', sa.Column('min_delay_seconds', sa.Integer(), server_default='10', nullable=False))
    op.add_column('groups', sa.Column('max_delay_seconds', sa.Integer(), server_default='40', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'max_delay_seconds')
    op.drop_column('groups', 'min_delay_seconds')
    op.drop_column('groups', 'context_messages_count')
    op.drop_column('groups', 'is_active')
    # ### end Alembic commands ###
